on:
  push:
    branches: 
      - master
name: Deploy master branch
jobs:
  onlyOnMasterBranch:
    name: Only on master branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm i
    - run: npx sls deploy
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
